glyphHeight  : 5
glyphWidth   : 3
symbolOff    : " " 
symbolOn     : "█"
timeDisplay  : "%H:%M:%S"
border       : 20
zoom         : "auto"  
centerX      : "center"
centerY      : "center" 

glyphs:
  - char       : "0"
    bits       : [7,5,5,5,7]

  - char       : "1"
    bits       : [4,4,4,4,4]

  - char       : "2"
    bits       : [7,4,7,1,7]

  - char       : "3"
    bits       : [7,4,7,4,7]

  - char       : "4"
    bits       : [5,5,7,4,4]

  - char       : "5"
    bits       : [7,1,7,4,7]

  - char       : "6"
    bits       : [7,1,7,5,7]

  - char       : "7"
    bits       : [7,4,4,4,4]

  - char       : "8"
    bits       : [7,5,7,5,7]

  - char       : "9"
    bits       : [7,5,7,4,7]

  - char       : ":"
    bits       : [0,2,0,2,0]

  - char       : "."
    bits       : [0,0,0,2,0]
